---
title: |
  \vspace*{\fill}
  \fontsize{36}{40}\selectfont \textbf {Predicting Customer Subscriptions}
author: |
  \fontsize{24}{28}\selectfont Seif H. Kungulio
date: |
  \fontsize{18}{22}\selectfont December 24, 2025
  \ \vspace*{\fill}
output: 
  pdf_document:
    latex_engine: xelatex
    toc: false
    highlight: espresso
    include:
      in_header: resources/header.tex
header-includes:
  # Font and color setup
  - \usepackage{xcolor}
  - \definecolor{brand}{HTML}{000000}
  - \definecolor{subbrand}{HTML}{212121}
  - \usepackage{titlesec}
  - \titleformat{\section}{\Large\bfseries\color{brand}}{\thesection}{1em}{}
  - \titleformat{\subsection}{\large\bfseries\color{subbrand}}{\thesubsection}{0.75em}{}
  - \usepackage[most]{tcolorbox}
  - \tcbset{colback=white, colframe=brand, coltitle=white, fonttitle=\bfseries}
  - \usepackage{fancyhdr}
  - \pagestyle{fancy}
  - \fancyhead[L]{\textcolor{brand}{Predicting Customer Subscriptions}}
  - \fancyhead[R]{\textcolor{subbrand}{Seif H. Kungulio}}
  - \fancyfoot[C]{\thepage}
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.width=12, fig.height=8)

# Set default CRAN mirror
options(repos = c(CRAN = "https://cloud.r-project.org"))

#Install the following libraries if required
# List of required packages
required_pkgs <- c("RCurl", "tidyverse", "caret", "randomForest", "xgboost", "pROC", "ROSE", "corrplot", "knitr")

# Install and load each package
for (pkg in required_pkgs) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    install.packages(pkg)
  }
  library(pkg, character.only = TRUE)
}

theme_set(theme_test(base_size = 14))
options(dplyr.summarise.inform = FALSE)
```

\pagenumbering{gobble}

\newpage
\thispagestyle{plain}
&nbsp;

\newpage
\pagenumbering{roman}
\tableofcontents

\newpage
\pagenumbering{arabic}

# **Business Understanding**
## Introduction

## Problem Statement

## Objectives


## Success Criteria



\newpage

# **Data Understanding**
## Data Collection

## Data Description

## Initial Data Exploration

## Data Quality Assessment

## Missing Values Analysis

## Outlier Detection

## Correlation Analysis

## Summary of Findings




\newpage

# **Data Preparation**
## Data Cleaning

## Feature Engineering

## Data Transformation

## Data Splitting

## Summary of Prepared Data





\newpage

# **Modeling**
## Model Selection


## Model Training


## Hyperparameter Tuning


## Model Comparison


## Final Model Selection


## Model Interpretation


## Feature Importance


## Model Validation


## Summary of Modeling Results




\newpage

# **Evaluation**
## Performance Metrics


## Business Impact Analysis


## Limitations and Assumptions


## Recommendations




\newpage

# **Deployment**
## Deployment Strategy


## Implementation Plan


## Monitoring and Maintenance Plan


## Summary of Deployment Plan


## Future Work


## Acknowledgments

## References


## Appendices


## R Session Information


## Code Repository


## Contact Information


## About the Author


## Glossary





\newpage

# **Conclusion**


